# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['test_2_longs_on_same_day 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 6.0,
        'entry_order_price': 4.0,
        'entry_price': 4.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:39:59+0000', tz='UTC')"),
        'exit_price': 2.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 4.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:39:59+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 2.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 2.0,
        'target_hit': False,
        'target_price': 6.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 8.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:43:19+0000', tz='UTC')"),
        'exit_price': 4.0,
        'max_distance': 17.99,
        'max_r': 8.99,
        'max_target_exit_price': 19.99,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 15:16:40+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 2.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 0.0,
        'target_hit': True,
        'target_price': 4.0,
        'target_r': 1.0,
        'theoretical_r': 1.0,
        'time_close': False
    }
]

snapshots['test_levels_on_open_quote 1'] = [
]

snapshots['test_long_and_short_on_same_day 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 15.0,
        'entry_price': 15.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:58:20+0000', tz='UTC')"),
        'exit_price': 14.0,
        'max_distance': 5.0,
        'max_r': 2.5,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 15:10:00+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': 0.5,
        'stop_hit': False,
        'stop_price': 17.0,
        'target_hit': True,
        'target_price': 14.0,
        'target_r': 0.5,
        'theoretical_r': 0.5,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 5.0,
        'entry_price': 5.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:19+0000', tz='UTC')"),
        'exit_price': 6.0,
        'max_distance': 10.99,
        'max_r': 5.5,
        'max_target_exit_price': 15.99,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 15:00:00+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': 0.5,
        'stop_hit': False,
        'stop_price': 3.0,
        'target_hit': True,
        'target_price': 6.0,
        'target_r': 0.5,
        'theoretical_r': 0.5,
        'time_close': False
    }
]

snapshots['test_long_and_short_skip_level 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 15.0,
        'entry_price': 15.01,
        'entry_time': GenericRepr("Timestamp('2020-12-10 15:01:41+0000', tz='UTC')"),
        'exit_price': 16.02,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 15.01,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 15:01:41+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.01,
        'stop_hit': True,
        'stop_price': 16.01,
        'target_hit': False,
        'target_price': 14.01,
        'target_r': 1.0,
        'theoretical_r': -1.02,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 5.0,
        'entry_price': 4.99,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:21+0000', tz='UTC')"),
        'exit_price': 3.98,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 4.99,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:21+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.01,
        'stop_hit': True,
        'stop_price': 3.99,
        'target_hit': False,
        'target_price': 5.99,
        'target_r': 1.0,
        'theoretical_r': -1.02,
        'time_close': False
    }
]

snapshots['test_multi_parameter_long_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 9.0,
        'target_hit': False,
        'target_price': 11.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 9.0,
        'target_hit': False,
        'target_price': 20.0,
        'target_r': 10.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 8.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 8.0,
        'target_hit': False,
        'target_price': 11.0,
        'target_r': 0.5,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 8.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 8.0,
        'target_hit': False,
        'target_price': 20.0,
        'target_r': 5.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 5.0,
        'max_r': 1.67,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 3.0,
        'parameter_target': 1.0,
        'r': 0.33,
        'stop_hit': False,
        'stop_price': 7.0,
        'target_hit': True,
        'target_price': 11.0,
        'target_r': 0.33,
        'theoretical_r': 0.33,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 15.0,
        'max_distance': 5.0,
        'max_r': 1.67,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 3.0,
        'parameter_target': 10.0,
        'r': 1.67,
        'stop_hit': False,
        'stop_price': 7.0,
        'target_hit': False,
        'target_price': 20.0,
        'target_r': 3.33,
        'theoretical_r': 1.67,
        'time_close': True
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 5.0,
        'max_r': 1.25,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 4.0,
        'parameter_target': 1.0,
        'r': 0.25,
        'stop_hit': False,
        'stop_price': 6.0,
        'target_hit': True,
        'target_price': 11.0,
        'target_r': 0.25,
        'theoretical_r': 0.25,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 15.0,
        'max_distance': 5.0,
        'max_r': 1.25,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 4.0,
        'parameter_target': 10.0,
        'r': 1.25,
        'stop_hit': False,
        'stop_price': 6.0,
        'target_hit': False,
        'target_price': 20.0,
        'target_r': 2.5,
        'theoretical_r': 1.25,
        'time_close': True
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 10.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 10.0,
        'target_hit': False,
        'target_price': 12.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 10.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 1.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 10.0,
        'target_hit': False,
        'target_price': 21.0,
        'target_r': 10.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 9.0,
        'target_hit': False,
        'target_price': 12.0,
        'target_r': 0.5,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 2.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 9.0,
        'target_hit': False,
        'target_price': 21.0,
        'target_r': 5.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 8.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 3.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 8.0,
        'target_hit': False,
        'target_price': 12.0,
        'target_r': 0.33,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 8.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 11.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 3.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 8.0,
        'target_hit': False,
        'target_price': 21.0,
        'target_r': 3.33,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 12.0,
        'max_distance': 4.0,
        'max_r': 1.0,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 4.0,
        'parameter_target': 1.0,
        'r': 0.25,
        'stop_hit': False,
        'stop_price': 7.0,
        'target_hit': True,
        'target_price': 12.0,
        'target_r': 0.25,
        'theoretical_r': 0.25,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 4.0,
        'entry_order_price': 11.0,
        'entry_price': 11.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 15.0,
        'max_distance': 4.0,
        'max_r': 1.0,
        'max_target_exit_price': 15.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 4.0,
        'parameter_target': 10.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 7.0,
        'target_hit': False,
        'target_price': 21.0,
        'target_r': 2.5,
        'theoretical_r': 1.0,
        'time_close': True
    }
]

snapshots['test_multi_parameter_short_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 11.0,
        'target_hit': False,
        'target_price': 9.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 11.0,
        'target_hit': False,
        'target_price': 0.0,
        'target_r': 10.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 12.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 12.0,
        'target_hit': False,
        'target_price': 9.0,
        'target_r': 0.5,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 12.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 10.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 2.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 12.0,
        'target_hit': False,
        'target_price': 0.0,
        'target_r': 5.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 5.0,
        'max_r': 1.67,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 3.0,
        'parameter_target': 1.0,
        'r': 0.33,
        'stop_hit': False,
        'stop_price': 13.0,
        'target_hit': True,
        'target_price': 9.0,
        'target_r': 0.33,
        'theoretical_r': 0.33,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 5.0,
        'max_distance': 5.0,
        'max_r': 1.67,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 3.0,
        'parameter_target': 10.0,
        'r': 1.67,
        'stop_hit': False,
        'stop_price': 13.0,
        'target_hit': False,
        'target_price': 0.0,
        'target_r': 3.33,
        'theoretical_r': 1.67,
        'time_close': True
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 9.0,
        'max_distance': 5.0,
        'max_r': 1.25,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 4.0,
        'parameter_target': 1.0,
        'r': 0.25,
        'stop_hit': False,
        'stop_price': 14.0,
        'target_hit': True,
        'target_price': 9.0,
        'target_r': 0.25,
        'theoretical_r': 0.25,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 5.0,
        'entry_order_price': 10.0,
        'entry_price': 10.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:38:20+0000', tz='UTC')"),
        'exit_price': 5.0,
        'max_distance': 5.0,
        'max_r': 1.25,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 4.0,
        'parameter_target': 10.0,
        'r': 1.25,
        'stop_hit': False,
        'stop_price': 14.0,
        'target_hit': False,
        'target_price': 0.0,
        'target_r': 2.5,
        'theoretical_r': 1.25,
        'time_close': True
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 10.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 10.0,
        'target_hit': False,
        'target_price': 8.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 10.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 1.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 10.0,
        'target_hit': False,
        'target_price': -1.0,
        'target_r': 10.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 2.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 11.0,
        'target_hit': False,
        'target_price': 8.0,
        'target_r': 0.5,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 11.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 2.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 11.0,
        'target_hit': False,
        'target_price': -1.0,
        'target_r': 5.0,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 12.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 3.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 12.0,
        'target_hit': False,
        'target_price': 8.0,
        'target_r': 0.33,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 12.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 9.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 3.0,
        'parameter_target': 10.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 12.0,
        'target_hit': False,
        'target_price': -1.0,
        'target_r': 3.33,
        'theoretical_r': -1.0,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 8.0,
        'max_distance': 4.0,
        'max_r': 1.0,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 4.0,
        'parameter_target': 1.0,
        'r': 0.25,
        'stop_hit': False,
        'stop_price': 13.0,
        'target_hit': True,
        'target_price': 8.0,
        'target_r': 0.25,
        'theoretical_r': 0.25,
        'time_close': False
    },
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 4.0,
        'entry_order_price': 9.0,
        'entry_price': 9.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:36:40+0000', tz='UTC')"),
        'exit_price': 5.0,
        'max_distance': 4.0,
        'max_r': 1.0,
        'max_target_exit_price': 5.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:53:20+0000', tz='UTC')"),
        'parameter_buffer': 1.0,
        'parameter_stop': 4.0,
        'parameter_target': 10.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 13.0,
        'target_hit': False,
        'target_price': -1.0,
        'target_r': 2.5,
        'theoretical_r': 1.0,
        'time_close': True
    }
]

snapshots['test_stop_hit_on_long_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 1.0,
        'max_distance': 0.9,
        'max_r': 0.9,
        'max_target_exit_price': 2.9,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:10+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 1.0,
        'target_hit': False,
        'target_price': 3.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    }
]

snapshots['test_stop_hit_on_long_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 1.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 2.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 1.0,
        'target_hit': False,
        'target_price': 3.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    }
]

snapshots['test_stop_hit_on_short_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 3.0,
        'max_distance': 0.9,
        'max_r': 0.9,
        'max_target_exit_price': 1.1,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:10+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 3.0,
        'target_hit': False,
        'target_price': 1.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    }
]

snapshots['test_stop_hit_on_short_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 3.0,
        'max_distance': 0.0,
        'max_r': 0.0,
        'max_target_exit_price': 2.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': -1.0,
        'stop_hit': True,
        'stop_price': 3.0,
        'target_hit': False,
        'target_price': 1.0,
        'target_r': 1.0,
        'theoretical_r': -1.0,
        'time_close': False
    }
]

snapshots['test_target_hit_on_long_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 3.0,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 3.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 1.0,
        'target_hit': True,
        'target_price': 3.0,
        'target_r': 1.0,
        'theoretical_r': 1.0,
        'time_close': False
    }
]

snapshots['test_target_hit_on_long_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 0.9,
        'entry_order_price': 2.1,
        'entry_price': 2.1,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:30+0000', tz='UTC')"),
        'exit_price': 3.1,
        'max_distance': 1.2,
        'max_r': 1.2,
        'max_target_exit_price': 3.3,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:50+0000', tz='UTC')"),
        'parameter_buffer': 0.1,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 1.1,
        'target_hit': True,
        'target_price': 3.1,
        'target_r': 1.0,
        'theoretical_r': 1.0,
        'time_close': False
    }
]

snapshots['test_target_hit_on_short_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 1.0,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 1.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 3.0,
        'target_hit': True,
        'target_price': 1.0,
        'target_r': 1.0,
        'theoretical_r': 1.0,
        'time_close': False
    }
]

snapshots['test_target_hit_on_short_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 0.9,
        'entry_order_price': 1.9,
        'entry_price': 1.9,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:30+0000', tz='UTC')"),
        'exit_price': 0.9,
        'max_distance': 1.2,
        'max_r': 1.2,
        'max_target_exit_price': 0.7,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:50+0000', tz='UTC')"),
        'parameter_buffer': 0.1,
        'parameter_stop': 1.0,
        'parameter_target': 1.0,
        'r': 1.0,
        'stop_hit': False,
        'stop_price': 2.9,
        'target_hit': True,
        'target_price': 0.9,
        'target_r': 1.0,
        'theoretical_r': 1.0,
        'time_close': False
    }
]

snapshots['test_time_close_on_long_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 2.5,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 3.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.1,
        'r': 0.5,
        'stop_hit': False,
        'stop_price': 1.0,
        'target_hit': False,
        'target_price': 3.1,
        'target_r': 1.1,
        'theoretical_r': 0.5,
        'time_close': True
    }
]

snapshots['test_time_close_on_long_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'long',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 1.1,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 3.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.1,
        'r': -0.9,
        'stop_hit': False,
        'stop_price': 1.0,
        'target_hit': False,
        'target_price': 3.1,
        'target_r': 1.1,
        'theoretical_r': -0.9,
        'time_close': True
    }
]

snapshots['test_time_close_on_short_1 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 1.5,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 1.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.1,
        'r': 0.5,
        'stop_hit': False,
        'stop_price': 3.0,
        'target_hit': False,
        'target_price': 0.9,
        'target_r': 1.1,
        'theoretical_r': 0.5,
        'time_close': True
    }
]

snapshots['test_time_close_on_short_2 1'] = [
    {
        'date': '01/01/1994',
        'direction': 'short',
        'distance': 1.0,
        'entry_order_price': 2.0,
        'entry_price': 2.0,
        'entry_time': GenericRepr("Timestamp('2020-12-10 14:31:40+0000', tz='UTC')"),
        'exit_price': 2.9,
        'max_distance': 1.0,
        'max_r': 1.0,
        'max_target_exit_price': 1.0,
        'max_target_exit_time': GenericRepr("Timestamp('2020-12-10 14:33:20+0000', tz='UTC')"),
        'parameter_buffer': 0.0,
        'parameter_stop': 1.0,
        'parameter_target': 1.1,
        'r': -0.9,
        'stop_hit': False,
        'stop_price': 3.0,
        'target_hit': False,
        'target_price': 0.9,
        'target_r': 1.1,
        'theoretical_r': -0.9,
        'time_close': True
    }
]
